[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_zk_dao = "GVpMARaodGLrQKyCven2ENBSL5WbCRHDzVvCGdkUz2fk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
